### ISSUE TITLE
Two more mundane details in the README

### ISSUE THREAD

**Issue by FrankRuben** [basic-gongfu/cixl#10]
Hi,
as the title says, two more small ones - just big enough to leave them unmentioned:

1. `10 {+ 42,} for` doesn't work for me, whereas `10 { 42 + } for` does.

1. `'foo' {int ++ char} map str` doesn't work for me, whereas `'foo' {int ++ char} map stack str` does.

HTH, Frank

**Comment by basic-gongfu** [comment]
Nice catch :)

The first one is a left-over from ancient times when Cixl supported switching between infix/prefix/postfix. And the second a result of tightened type declarations from adding generic types. Since lambdas don't infer type signatures yet, map has no way of knowing what kind of iterator it is in advance; which doesn't work for str since it wants a char iterator. Stacks infer their types from incoming items when constructed from sequences which is why your proposed solution works.
```'foo' {int ++ char} map #nil join``` would be another, more generic way to get the same result without copying items to a stack first.

Keep 'em coming!
